### ISSUE TITLE
Cannot log into/transact in sqlledger

### ISSUE THREAD

**Issue by PeterAOBell** [drnoa/sqlledger_docker#6]
Attempting to log in via ledger123/login.pl results in a lengthy delay before producing a 504 error. 

Looking in /var/log/apache2/error.log, I find the following which appears to relate to my login attempt: 
`[Thu Nov 23 12:26:41.388971 2017] [cgid:error] [pid 23:tid 22949691954944] [client 172.22.1.15:39222] Script timed out before returning headers: login.pl, referer: http://tower:8888/ledger123/login.pl
DBI connect('dbname=ledgercart;host=tower;port=8888','postgres',...) failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request. at SL/User.pm line 103.
Error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Compilation failed in require at /var/www/html/ledger123/login.pl line 92.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at SL/Form.pm line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE document}/ at SL/Form.pm line 628.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at SL/Form.pm line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE document}/ at SL/Form.pm line 628.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at SL/Form.pm line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE document}/ at SL/Form.pm line 628.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at SL/Form.pm line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE document}/ at SL/Form.pm line 628.
`

Something very similar is logged if I attempt to create a dataset in admin.pl

It appears that the application is having difficulty communicating with the database.

I have installed the docker on my Mint desktop machine and on my headless slackware-based server, already running several docker containers, but I encounter the same problem in both environments.

What am I doing wrong?  All advice is gratefully received.

**Comment by drnoa** [comment]
Hi PeterAOBell 
I will try to figure out where the problem comes from. I'll keep you updated.

Have you tried the docker-hub version "docker pull drnoa/sqlledger-docker" or did you use the dockerfile iteself?

**Comment by drnoa** [comment]
OK i tried the following way:
* I pulled the latest build from docker hub: docker pull drnoa/sqlledger-docker
* I started the container: docker run drnoa/sqlledger-docker
* I open the admin site: http://172.17.0.3/ledger123/admin.pl using admin123 as password
* I create a new user with the following db connection settings: Driver: Pg, Dataset: ledgercart, User: sqlledger, Host: localhost, Port <emty>, Password: docker
* I log in to the sqlledger gui on http://172.17.0.3/ledger123/login.pl with my user and password.

can you try this?
